modLoader = "javafml" #mandatory
loaderVersion = "[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "LGPLv3" # Review your options at https://choosealicense.com/.
issueTrackerURL="https://github.com/CorgiTaco/Oh-The-Trees-Youll-Grow/issues" #optional
[[mods]] #mandatory
modId = "ohthetreesyoullgrow" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
displayURL="https://curseforge.com/minecraft/mc-mods/oh-the-trees-youll-grow" #optional (displayed in the mod UI)
logoFile = "logo.png" #optional (needs to be in the root of your mod jar (root of your 'resources' folder))
credits = "" #optional
authors = "${mod_author}" #optional
description = '''
A Minecraft library that aims to give users incredible configurability by allowing the creation of trees with Minecraft's structure template `.nbt` files.
''' #mandatory (Supports multiline text)

[[dependencies.ohthetreesyoullgrow]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[46,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.ohthetreesyoullgrow]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
