# Important Notes:
# Every field you add must be added to `buildSrc/src/main/kotlin/multiloader-common.gradle.kts` expandProps map.

# Project
version=10.1.2-a
group=dev.corgitaco.ohthetreesyoullgrow
java_version=25

# Common
minecraft_version=26.1.2
mod_name=Oh The Trees You'll Grow
mod_author=Corgi Taco
mod_id=ohthetreesyoullgrow
license=MPL 2.0
credits=
description=A Minecraft library that aims to give users incredible configurability by allowing the creation of trees with Minecraft's structure template `.nbt` files.
minecraft_version_range=[26.1, 26.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.152.1+26.1.2
fabric_loader_version=0.18.4

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.76
neoforge_loader_version_range=[4,)

forge_version=64.0.10

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Upload Settings
curseforge_id=962544
modrinth_id=g8NOG5OR