modLoader = "javafml" #mandatory
loaderVersion = "[1,)" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "LGPLv3" # Review your options at https://choosealicense.com/.
issueTrackerURL="https://github.com/CorgiTaco/Oh-The-Trees-Youll-Grow/issues" #optional
[[mods]] #mandatory
modId = "ohthetreesyoullgrow" #mandatory
version = "${version}" #mandatory
displayName = "Oh The Trees You'll Grow" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
displayURL="https://curseforge.com/minecraft/mc-mods/oh-the-trees-youll-grow" #optional (displayed in the mod UI)
logoFile = "logo.png" #optional (needs to be in the root of your mod jar (root of your 'resources' folder))
credits = "Joseph T. McQuigg (JT122406)" #optional
authors = "Corgi Taco" #optional
description = '''
A Minecraft library that aims to give users incredible configurability by allowing the creation of trees with Minecraft's structure template `.nbt` files.
''' #mandatory (Supports multiline text)

[[dependencies.ohthetreesyoullgrow]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
versionRange = "[20.4,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.ohthetreesyoullgrow]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "ohthetreesyoullgrow.mixins.json"
